# Generated by Django 3.1.5 on 2021-02-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210201_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='featured_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='for_gender',
        ),
        migrations.AddField(
            model_name='category',
            name='feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='for_gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('Both', 'Both')], default='men', max_length=10),
        ),
    ]
