# Generated by Django 3.1.5 on 2021-02-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210203_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='category',
            name='for_gender',
        ),
        migrations.AddField(
            model_name='category',
            name='featured_in',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='for_gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10),
        ),
    ]
