# Generated by Django 3.1.5 on 2021-02-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210206_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
