# Generated by Django 3.1.5 on 2021-02-13 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210213_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='summary',
        ),
    ]
