# Generated by Django 3.1.7 on 2021-03-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_review_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(choices=[(1, 'Bkash'), (2, 'Cash On Delivery')], default=2)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cancellion_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Ordered'), (1, 'Pending'), (2, 'Processing'), (3, 'Delivered'), (-1, 'Cancelled')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('both', 'Both')], default='men', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment'),
        ),
    ]
