# Generated by Django 3.1.7 on 2021-03-24 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210322_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAndPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=500)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_option', models.IntegerField(choices=[(1, 'Bkash'), (2, 'Cash On Delivery')], default=1)),
                ('bkash_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.shippingandpayment'),
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
