# Generated by Django 3.1.7 on 2021-03-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210327_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingandbilling',
            name='zip_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
