# Generated by Django 3.1.7 on 2021-03-29 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210327_0400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default_shipping',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.shippingandbilling'),
        ),
    ]
