# Generated by Django 3.1.7 on 2021-03-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210329_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingandbilling',
            name='shipping_charge',
            field=models.IntegerField(default=0),
        ),
    ]
