# Generated by Django 3.1.7 on 2021-03-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_shippingandbilling_shipping_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingandbilling',
            name='zip_code',
        ),
    ]
