# Generated by Django 3.1.7 on 2021-04-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_shippingandbilling_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
