# Generated by Django 3.1 on 2021-04-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210407_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingandbilling',
            old_name='street_address',
            new_name='address',
        ),
    ]
